### ISSUE TITLE
Cannot visualize the annotation

### ISSUE THREAD

**Issue by guyuchao** [WesleyHsieh0806/TAO-Amodal#5]
I cannot visualize using the given command because no video has been processed. The problem is that the **video** is a directory name, while **args.video_name** contains image_name, which do not match. Can you help fix this problem?

<img width="739" alt="Screenshot 2024-05-01 at 9 12 46 PM" src="https://github.com/WesleyHsieh0806/TAO-Amodal/assets/31696690/f6fe74ff-7826-4f73-a576-979dbb30019c">

<img width="736" alt="Screenshot 2024-05-01 at 9 10 17 PM" src="https://github.com/WesleyHsieh0806/TAO-Amodal/assets/31696690/35653820-3532-4e8e-84cc-b2557b2266b7">

<img width="739" alt="Screenshot 2024-05-01 at 9 14 08 PM" src="https://github.com/WesleyHsieh0806/TAO-Amodal/assets/31696690/adb58725-05e8-45c4-90bc-4884d3371dc6">

**Comment by WesleyHsieh0806** [comment]
Sorry, I don't really get what you mean. Can you print the value of `args.video_name`?
When you run the provided commands, video names will be randomly selected in `get_video_name(args) ` at this [line](https://github.com/WesleyHsieh0806/TAO-Amodal/blob/main/visualization/vis_amodal_mask_videos.py#L316). 

The video frames belonging to the selected videos will be stored in `videos[video]` as shown in your snapshot. If no video is being processed, normally it's because you provided the wrong path to `--annotations`, `--mask-annotations` or `--images-dir`.
